bunk/urls.py
from django.conf.urls import url 
from .views import AllBunks, bunkView, userBunksView, newUser, login, AllUsers

app_name = 'bunk'

urlpatterns = [
    #/ index view, shows all bunks
    url(r'^$', AllBunks.as_view(), name = 'bunks'),

    #/{id}, shows all bunks involving a user with a specified id
    url(r'^(?P<userID>[0-9]+)/$', userBunksView, name = 'userbunk'),

    #bunk/, allows the user to chose someone to bunk 
    url(r'^bunk/$', bunkView, name = 'bunk'),

    #/signup, allows the users to register 
    url(r'^register/$', newUser, name = 'register'),

    #/login logs in a user
    url(r'^login/', login, name = 'login'),

    #/users gets all users
    url(r'^users/$', AllUsers.as_view(), name = 'allUsers')
]

jitterbunk/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('bunk.urls'))
]

jitterbunk_rewrite/jitterbunk_rewrite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core'))
]

bunk/models.py
from django.db import models
from datetime import datetime
# Create your models here.

USER_MAX_LEN = 50
IMG_URL_MAX_LEN = 200

class User(models.Model):
    username = models.CharField(max_length = USER_MAX_LEN)
    imgurl = models.CharField(max_length = IMG_URL_MAX_LEN)

    def __str__(self):
        return(self.username)

def datetimeToString(time: datetime):
    return time.strftime('%D at %H:%M')

class Bunk(models.Model):
    sender = models.ForeignKey(User, on_delete = models.CASCADE, related_name = 'sender')
    receiver = models.ForeignKey(User, on_delete = models.CASCADE, related_name = 'receiver')
    sentdate = models.DateTimeField(auto_now_add = True, blank = True)

    def getSender(self):
        return(User.objects.filter(id = sender)[0])
    
    def getReceiver(self):
        return(User.objects.filter(id = receiver)[0])

bunk/views.py
from django.db.models import Q
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.views.generic import ListView, DetailView
from .models import Bunk, User
from django.views.decorators.csrf import csrf_exempt
from django.core.urlresolvers import reverse
import json

#view to display all bunks made
class AllBunks(ListView):
    template_name = 'bunks.html'
    context_object_name = 'allbunks'

    def get_queryset(self):
        return Bunk.objects.all().order_by('-sentdate')

#view to display all bunks for a specific user
def userBunksView(request, userID):
    print(userID)
    userBunks = Bunk.objects.filter(Q(sender_id = userID) | Q(receiver_id = userID))
    context = {}
    if len(userBunks):
        context = {
            'bunks': userBunks,
            'userID': userID,
            'name': User.objects.filter(id = userID)[0].username
        }
    else:
        context = {
            'bunks': userBunks,
            'userID': userID,
        }
    return(render(request, "userbunk.html", context))

#view to allow a user to send a bunk to another user
def bunkView(request):
    sender = request.session['id']
    if request.method == "GET":
        context = {
            'sender': sender,
            'username': User.objects.all().filter(pk = sender)[0].username,
            'targets': User.objects.all().filter(
                ~Q(id = sender)
            )
        }
        return(render(request, 'bunk.html', context))
    elif request.method == "POST":
        bunk = Bunk(sender_id = sender, receiver_id = request.POST['target'])
        bunk.save()
        return(HttpResponseRedirect('/'))

#view to handle new users registering
def newUser(request):
    if request.method == "POST":
        context = {'error': "You must enter a profile picture and username"}
        if request.POST['profpic'] and request.POST['username']:
            user = User(username = request.POST['username'], imgurl = request.POST['profpic'])
            user.save()
            request.session['id'] = user.id
            return(HttpResponseRedirect("/"))
        else:
            return(HttpResponseRedirect("/signup"))
    elif request.method == "GET":
        return(render(request, 'signup.html'))

#view to handle users logging in
def login(request):
    users = []
    for u in User.objects.all():
        user = {
            'username': u.username,
            'imgurl': u.imgurl,
            'id': u.id
        }
        users.append(user)
    context = {'users': users}
    if request.method == "POST":
        print(request.POST)
        id = request.POST['userID']
        if len(User.objects.filter(id = id)):
            request.session['id'] = id
            return(HttpResponseRedirect("/"))
        context['error'] = "Invalid user"
    return(render(request, "login.html", context))


class AllUsers(ListView):
    template_name = 'allUsers.html'
    context_object_name = 'users'
    def get_queryset(self):
        return(User.objects.order_by('username'))

bunk/templates/allUsers.html
{% load static %}
<link rel="stylesheet" type = "text/css" href="{% static 'bunk/bunk.css' %}">
<link rel="stylesheet" type = "text/css" href="{% static 'bunk/allusers.css' %}">

<h1>All users!</h1>

<div id = "people">
    {% for user in users%}
        <a href="/{{user.id}}">
            <img src = "{{user.imgurl}}">
        </a>
    {% endfor %}

</div>

bunk/templates/bunk.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Document</title>
        {% load static %}
        <link rel="stylesheet" type = "text/css" href="{% static 'bunk/bunk.css' %}">
        <link rel="stylesheet" type = "text/css" href="{% static 'bunk/nav.css' %}">
    </head>
    <body>
        <h1>{{username}}</h1>
        <form action="{% url 'bunk:bunk' %}" method="POST">
            {% csrf_token %}
            <br/>
            {% for target in targets%}
                <label for = "target{{forloop.counter}}">
                    <input type = "radio" name = "target" id = "target{{forloop.counter}}" value = "{{target.id}}"/>
                    <img src="{{target.imgurl}}" alt="{{target.username}}">
                </label>
                <br/>
            {% endfor %}

            <input type="submit" name="submit" value="submit" id="submitBtn">
        </form>
    </body>

</html>

bunk/templates/bunks.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    {% load static %}
    <link rel="stylesheet" type = "text/css" href="{% static 'bunk/style.css' %}">
    <link rel="stylesheet" type = "text/css" href="{% static 'bunk/nav.css' %}">
</head>

<body>
    {% if allbunks %}
        <div id = "bunkContainer">
            <h1 id = "bunkTitle">Bunks</h1>
            {% for bunk in allbunks %}
                <div class="bunk {% if forloop.counter|divisibleby:2 %}b{% else %}a{% endif %}" >
                    <span class = "timestamp_{% if forloop.counter|divisibleby:2 %}b{% else %}a{% endif %}">{{bunk.sentdate.month}}/{{bunk.sentdate.day}}/{{bunk.sentdate.year}}</span>
                    <a href="/{{bunk.sender.id}}">
                        <img class = "bunkImg" src="{{bunk.sender.imgurl}}" alt="Picture of {{bunk.sender.username}}">
                    </a>
                    
                    <span class = "bunked">BUNKED</span>

                    <a href="/{{bunk.receiver.id}}">
                        <img class = "bunkImg" src="{{bunk.receiver.imgurl}}" alt="Picture of {{bunk.receiver.username}}">
                    </a>    

                </div>
            {% endfor %}
        </div>
    {% else %}
        No Bunks found 😢
    {% endif %}
</body>

bunk/templates/login.html
{% load static %}
<link rel="stylesheet" type = "text/css" href="{% static 'bunk/login.css' %}">

<span id = "inputName">
    <input type="text" name="" id="name">
</span>

<form action="{% url 'bunk:login' %" id = "loginForm" method="POST">
    {% csrf_token %}
    <div id = "people">

    </div>
    <input type="submit" value="login">
</form>

<script>

    function filterUsers(users, key)
    {
        key = key.toLowerCase();
        let filter = users.filter((u) => {
            var username = u.username.toLowerCase();
            return(username.includes(key))
        })

        if(filter.length > 8)
        {
            filter = filter.slice(0, 8);
        }

        return(filter);
    }

    function updateUsers()
    {
        const key = userField.value;
        var users = {{users|safe}};
        users.sort((a, b) => {
            const aName = a.username;
            const bName = b.username;
            if(aName > bName)
            {
                return(1);
            }
            else if(aName < bName)
            {
                return(-1);
            }
            return(0);
        })
        users = filterUsers(users, key);
        const formField = document.getElementById("people");
        formField.innerHTML = '';

        users.forEach((user) => {

            label = document.createElement("label");

            btn = document.createElement("input");
            btn.setAttribute("value", user.id);
            btn.setAttribute("type", "radio");
            btn.setAttribute("alt", user.username);
            btn.setAttribute("name", "userID");

            img = document.createElement("img");
            img.setAttribute("src", user.imgurl);

            label.appendChild(btn);
            label.appendChild(img);

            formField.appendChild(label);
        })
    }

    const userField = document.getElementById("name");
    userField.addEventListener("input", (e) => {
        console.log("updating");
        updateUsers();
    }) 
    updateUsers();

</script>

bunk/templates/pagesetup.html
<div>
    <div id = "nav">
        <a href = "/"></a>

    </div>
    {% block content %}
    {% endblock %}
</div>

bunk/templates/signup.html
{% load static %}
<link rel="stylesheet" type = "text/css" href="{% static 'bunk/signup.css' %}">

<div id = "newUserForm">

    <form action = "{% url 'bunk:register' %}" method = "POST">
        {% csrf_token %}
        <input type="text" name="username" id="usernameField" placeholder="Username">
        <input type = "text" name = "profpic" id = "imgURL" placeholder = "profpicURL">
        <br/>
        <input type="submit" value="Submit">
    </form>
</div>

bunk/templates/userbunk.html
{% load static %}
<link rel="stylesheet" type = "text/css" href="{% static 'bunk/style.css' %}">

{% if bunks %}
<div id = "bunkContainer">
	<h1 id = "bunkTitle">{{name}}</h1>
	{% for bunk in bunks %}
		<div class="bunk {% if forloop.counter|divisibleby:2 %}b{% else %}a{% endif %}" >
			<span class = "timestamp_{% if forloop.counter|divisibleby:2 %}b{% else %}a{% endif %}">{{bunk.sentdate.month}}/{{bunk.sentdate.day}}/{{bunk.sentdate.year}}</span>
			<a href="/{{bunk.sender.id}}">
				<img class = "bunkImg" src="{{bunk.sender.imgurl}}" alt="Picture of {{bunk.sender.username}}">
			</a>
			
			<span class = "bunked">BUNKED</span>

			<a href="/{{bunk.receiver.id}}">
				<img class = "bunkImg" src="{{bunk.receiver.imgurl}}" alt="Picture of {{bunk.receiver.username}}">
			</a>    

		</div>
	{% endfor %}
</div>
{% else %}
		<div>
			<span class = "errorText">This user has no bunks!</span>
		</div>
{% endif %}